baseURL = "https://snitcher.dannorth.net"
languageCode = "en-gb"
title = "Little Snitch Rule Generator"
theme = "vanilla-bootstrap"

publishDir = "../docs"
staticDir = "static"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

